version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages
      - python/test

  lint:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Linter
          command: |
            flake8 src/
            flake8 test/

workflows:
  build_and_test:
    jobs:
      - build-and-test
      - lint