version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build: # this can be any name you choose
    executor: python/default
    steps:
      - checkout  # Fetch your source code
      - python/setup:
          version: 3.8  # Specify your desired Python version
      - python/install-packages:
          requirements-file: requirements.txt  # Install your project's dependencies
      - run:
          name: Build
          command: python src/main.py 

  lint:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Linter
          command: |
            flake8 src/

workflows:
  build_and_test:
    jobs:
      - build
      - lint