version: 2.1

orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0

jobs:
  build: # this can be any name you choose
    executor: python/default
    steps:
      - checkout  # Fetch your source code
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt # Install your project's dependencies
      - run:
          name: Build
          command: python main.py

  push-to-ecr:
    executor: aws-ecr/default
    steps:
      - aws-ecr/aws-auth:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          aws-region: us-east-1  # Replace with your AWS region

      - run:
          name: Build and Push Docker Image to ECR
          command: |
            docker build -t my-python-app .
            docker tag web-app:latest 227739336694.dkr.ecr.us-east-1.amazonaws.com/my-python-app:latest
            docker push 227739336694.dkr.ecr.us-east-1.amazonaws.com/web-app:latest

  lint:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Linter
          command: |
            flake8

workflows:
  build-and-lint:
    jobs:
      - build
      - push-to-ecr:
          aws-region: us-east-1  # Replace with your AWS region
          filters:
            branches:
              only:
                - main  # Adjust the branch name as needed
      - lint
